"""deleted PIN

Revision ID: 202fddfba29d
Revises: 6cc84cbb885d
Create Date: 2025-12-24 21:38:55.802019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '202fddfba29d'
down_revision: Union[str, Sequence[str], None] = '6cc84cbb885d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'PIN')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('PIN', mysql.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
