"""fixing colums and data types

Revision ID: 6cc84cbb885d
Revises: bf34b06f8c32
Create Date: 2025-12-24 21:08:06.711939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6cc84cbb885d'
down_revision: Union[str, Sequence[str], None] = 'bf34b06f8c32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('username'), table_name='logins')
    op.drop_table('logins')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logins',
    sa.Column('login_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(collation='utf8mb4_general_ci', length=50), nullable=False),
    sa.Column('password_hash', mysql.VARCHAR(collation='utf8mb4_general_ci', length=255), nullable=False),
    sa.Column('customer_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('last_login', mysql.TIMESTAMP(), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.customer_id'], name=op.f('logins_ibfk_1')),
    sa.PrimaryKeyConstraint('login_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('username'), 'logins', ['username'], unique=True)
    # ### end Alembic commands ###
