"""deleted is default field in portofolio table

Revision ID: d92b03de8a85
Revises: 22925a8e5952
Create Date: 2025-12-24 22:22:52.376917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd92b03de8a85'
down_revision: Union[str, Sequence[str], None] = '22925a8e5952'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portofolio_accounts', 'is_default')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portofolio_accounts', sa.Column('is_default', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
