"""revisi datatype mutasi

Revision ID: fac32bba0a8d
Revises: d92b03de8a85
Create Date: 2026-01-21 12:35:49.409757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fac32bba0a8d'
down_revision: Union[str, Sequence[str], None] = 'd92b03de8a85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mutations', 'mutation_type',
               existing_type=sa.Enum('Debit', 'Kredit', name='mutationtype'),
               type_=sa.Enum('Debit', 'Kredit', 'Refersal', 'SetorTunai', 'TarikTunai', name='mutationtype'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mutations', 'mutation_type',
               existing_type=sa.Enum('Debit', 'Kredit', 'Refersal', 'SetorTunai', 'TarikTunai', name='mutationtype'),
               type_=sa.Enum('Debit', 'Kredit', name='mutationtype'),
               existing_nullable=False)
    # ### end Alembic commands ###
